### ISSUE TITLE
Support draft-wright-json-schema-01 / draft6?

### ISSUE THREAD

**Issue by remexre** [santhosh-tekuri/jsonschema#1]
The newest draft is [draft-wright-json-schema-01](https://tools.ietf.org/html/draft-wright-json-schema-01), aka draft6. The largest change (I saw) was making `true` a valid schema equivalent to `{}`, and `false` a valid schema equivalent to `{ "not": {} }`.

**Comment by santhosh-tekuri** [comment]
I did a quick diff between draft4 and draft6 tests in https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/master/tests

It seems you are correct. draft6 allows boolean as valid schema. so only compilation has to be changed to support draft6

i will work on it.

**Comment by santhosh-tekuri** [comment]
seems there are quite a number additions and backward incompatible changes in draft6.

see complete changes in draft6 [here](http://json-schema.org/draft-06/json-schema-migration-faq.html)

**Comment by santhosh-tekuri** [comment]
draft6 support is in progress in  branch draft6

**Comment by santhosh-tekuri** [comment]
draft6 implementation finished in branch draft6

needs final code-review and documentation update before merging to master

**Comment by santhosh-tekuri** [comment]
merged draft6 into master.
