### ISSUE TITLE
Unnecessary `toStringKeys` when using `yaml.v3`

### ISSUE THREAD

**Issue by Gogomoe** [santhosh-tekuri/jsonschema#100]
Hi.
I'm using `jsonschema` for validating YAML documents. I noticed that in [Validating YAML Documents](https://github.com/santhosh-tekuri/jsonschema#validating-yaml-documents) section, there is a `toStringKeys` function. However, I found the function is useless when using `yaml.v3`:
- If the yaml doc only contains string keys, `yaml.Unmarshal` will returns `map[string]interface{}` for root and nested objects.
- If the yaml doc contains non-string keys, `schema.Validate` can also detected the wrong type.

Therefore, we can safely remove `toStringKeys`.
I finally realized it's used for `yaml.v2`, it's better to mention it to avoid confusing.

**Comment by santhosh-tekuri** [comment]
on testing it seems returns `map[string]interface{}` in v3

but I don't see anywhere it is mentioned that such change is done from v2 to v3. I don't find any release notes or documentation claiming that.

let me know if you find if such change in mentioned by library owner

**Comment by santhosh-tekuri** [comment]
having a glance at tests I found this: https://github.com/go-yaml/yaml/blob/v3.0.1/decode_test.go#L253-L257
which seems to contradict your claim.

**Comment by Gogomoe** [comment]
> let me know if you find if such change is mentioned by library owner

I found a [commit message](https://github.com/go-yaml/yaml/commit/14f799f057e7323ad4dfffa6f70641b091e51bf6) about it.

> #### Maps with string keys are now map[string] by default.
> Until now, decoding a map into an interface{} would produce a generic
> map[interface{}]interface{}. From now on, as long as all of the map keys
> are strings, they will automatically decode as map[string]interface{}.

It seems impossible to find a formal document about it, they are [missing documentation](https://github.com/go-yaml/yaml/issues/863) for a long time.

--- 
> having a glance at tests I found this: https://github.com/go-yaml/yaml/blob/v3.0.1/decode_test.go#L253-L257
> which seems to contradict your claim.

It only proves that the function can unmarshal to `map[interface{}]interface{}`. But it doesn't mean it will still return `map[interface{}]interface{}` instead of `map[string]interface{}` in the absence of a given type.

**Comment by santhosh-tekuri** [comment]
commits: 10132b8 56baa8b

I am still keeping this function. since some one using different yaml library may still find this function helpful.

added a note in readme that when yaml.v3 no conversion required

**Comment by Gogomoe** [comment]
> I am still keeping this function. since some one using different yaml library may still find this function helpful.
> added a note in readme that when using yaml.v3 no conversion required

Great work! That's exactly what I planed to do. Thanks!
