### ISSUE TITLE
Is Custom format checkers supported?

### ISSUE THREAD

**Issue by louiemiranda** [santhosh-tekuri/jsonschema#101]
I was testing https://github.com/xeipuuv/gojsonschema and decided to also check the current plugin, I needed to create a custom format checker that will lookup the database.

To be able to do it on the other plugin, just need to add

```
// Add it to the library
gojsonschema.FormatCheckers.Add("role", RoleFormatChecker{})
```

Then on the schema, just add format: "RoleFormatChecker".

Was wondering if there is similar too on this plugin?

Appreciate and guidance or help and not trying to compare the two as they are different, just wanted to know if it is achievable?

Thanks

**Comment by mgnsk** [comment]
I've been able to come by with this but it is global.
```go
jsonschema.Formats["email"] = func(v interface{}) bool {
	// custom email validation
}
```

**Comment by louiemiranda** [comment]
thanks for the tip @mgnsk. so for the actual schema, it would be like this format=email?

```
"email": {
            "type": "string",
            "format": "email",
          },
````

**Comment by mgnsk** [comment]
> thanks for the tip @mgnsk. so for the actual schema, it would be like this format=email?
> 
> ```
> "email": {
>             "type": "string",
>             "format": "email",
>           },
> ```

Yes, exactly.
