### ISSUE TITLE
Add warnings on json schema deprecated fields

### ISSUE THREAD

**Issue by adodon2go** [santhosh-tekuri/jsonschema#104]
In many schemas, you may want to deprecate fields and log warnings when these fields are used without causing a validation to fail entirely.
For draft 2019-09 JSON Schema, the **deprecated** annotation keyword was added.
As an enhancement, it would be great if those deprecated fields will be highlighted to the end user in the form of warnings. In this way they can be notified that support for those will be dropped soon and they need to adapt accordingly.

**Comment by santhosh-tekuri** [comment]
linting is no in scope of this project.
