### ISSUE TITLE
request: validate examples

### ISSUE THREAD

**Issue by pwmcintyre** [santhosh-tekuri/jsonschema#109]
hi

a feature request for you

given an example JSON Schema with an invalid example:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        }
    },
    "examples": [
        {
            "name": 1
        }
    ]
}
```

when running the validator:
```shell
$ go run github.com/santhosh-tekuri/jsonschema/cmd/jv@ea2d5ad ./example.json
$ echo $?                                                                  
0
```

then I would expect the above command to return the below error (but it does not)
```
[I#] [S#] doesn't validate with file:///tmp/example.json#
  [I#/name] [S#/properties/name/type] expected string, but got number
exit status 1
```

**Comment by santhosh-tekuri** [comment]
INVALID

`examples` is keyword for metadata annotations

as per specification, these keywords provide information for documentation. these keywords are not meant to be validated as per specification.

**Comment by lrworth** [comment]
It's not in the spec but it sure would be nice if this feature existed as an option.
