### ISSUE TITLE
Add draft-07 formats: iri

### ISSUE THREAD

**Issue by jcoyne** [santhosh-tekuri/jsonschema#11]
http://json-schema.org/draft-07/json-schema-release-notes.html#formats

I'm particularly interested in `iri`

**Comment by santhosh-tekuri** [comment]
"net/url/url.go" in standard lib implements RFC 3986
IRI requires RFC 3987

but it seems, url.go seems to work for IRI in most cases.

so you can simply register "uri" as "iri" as below:

```go
fun init() {
    formats.Register("iri", formats.IsURI)
}
```
