### ISSUE TITLE
Can not install v5.2.0

### ISSUE THREAD

**Issue by reitzig** [santhosh-tekuri/jsonschema#112]
This command used to work before:

```bash
go install github.com/santhosh-tekuri/jsonschema/v5/cmd/jv@v5.1.1
```

From diffing the docs, I see that it should now be:

```bash
go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v5.2.0
```

Not only does that now require Git (why?), but it also doesn't work:

```
go: github.com/santhosh-tekuri/jsonschema/cmd/jv@v5.2.0: github.com/santhosh-tekuri/jsonschema/cmd/jv@v5.2.0: invalid version: unknown revision cmd/jv/v5.2.0
```

What's the correct command to use now?

FWIW, I don't want to use `latest` since I pin versions and have Renovate bump them explicitly.

**Comment by reitzig** [comment]
Ah:

```bash
 # go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
go: downloading github.com/santhosh-tekuri/jsonschema/cmd/jv v0.3.1
go: downloading github.com/santhosh-tekuri/jsonschema v1.2.4
go: downloading github.com/santhosh-tekuri/jsonschema/v5 v5.1.1
go: downloading gopkg.in/yaml.v2 v2.4.0
```

Seems like something wasn't bumped correctly. Is the problem that [santhosh-tekuri/jsonschema:cmd/jv/go.mod](https://github.com/santhosh-tekuri/jsonschema/blob/master/cmd/jv/go.mod) still contains

```
require (
	github.com/santhosh-tekuri/jsonschema/v5 v5.1.1
)
```

**Comment by santhosh-tekuri** [comment]
yes. you are correct. corrected it.

now you can install it using one of the following commands:

```
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v0.4.0
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
```

note: the go.mod version of jv is `v0.4.0` where as jsonschema is `v5.2.0`

both are independent go modules

**Comment by reitzig** [comment]
I see, thanks for clarifying and fixing the issue at hand!

```bash
go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v0.4.0
```

does indeed work as expected.

That said, if you'll permit a follow-up: since the GitHub Releases use the versions of `jsonschema`, how can I configure Renovate/Dependabot so they can determine the current version of `jv`? :thinking:

**Comment by santhosh-tekuri** [comment]
I am not familiar with the tools you mentioned.

I have made GitHub release for jv https://github.com/santhosh-tekuri/jsonschema/releases/tag/cmd%2Fjv%2Fv0.4.0
let me know if that helps

**Comment by santhosh-tekuri** [comment]
may be using `gomod` package-manager could work for you:

https://gist.github.com/magnetikonline/6f215db058e327905bce66c37f92426c

**Comment by santhosh-tekuri** [comment]
If you are just interested in cli version, you may like [boon cli](https://github.com/santhosh-tekuri/boon#clil)

this is port of this library to rust language.
