### ISSUE TITLE
consider exposing a resolver that can handle any URL 

### ISSUE THREAD

**Issue by gaffo** [santhosh-tekuri/jsonschema#12]
The current loading / resource mechanism requires one to know all of the urls by default... consider providing a way to provide a resource that can just answer any url or return not found and then allow people to just implement multiple resolvers with a priority order. Such as "local FS", then "web"

**Comment by handrews** [comment]
There are some clarifications on loading, caching, and referencing in the [latest draft](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.3).  I'm not 100% sure they are relevant as I'm not quite sure what the request is here, but it seems like it is related to providing different ways to load and cache schemas from various sources other than just looking at the URI scheme.  e.g. loading schemas from the local FS even though the URIs have a scheme of `https://`.

**Comment by gaffo** [comment]
Yes that's a good summary, a way to load from various "repositories" more
easily. Like a zip.

**Comment by gaffo** [comment]
More importantly without having it affect the refs.

**Comment by santhosh-tekuri** [comment]
you can override default resolver as follows:

```go
loader.Load = func(url string) (io.ReadCloser, error) {
    // TODO
}
```

**Comment by santhosh-tekuri** [comment]
FYI, loading schemas from the local FS even though the URIs have a scheme of `https://` can be done without overriding resolver:

```go
r, err := os.Open("schemas/test.json")
if err!=nil {
    panic(err)
}
err = compiler.AddResource("https://example.com/test.json", reader)
```
