### ISSUE TITLE
Feature request: Pass custom compiler into "convenience" functions like CompileString

### ISSUE THREAD

**Issue by yannh** [santhosh-tekuri/jsonschema#120]
Hello :wave:  A [bug](https://github.com/yannh/kubeconform/issues/217) was reported to Kubeconform recently which was caused by us incorrectly using this library, and defaulting to an incorrect draft version of jsonschema. Here is[ the patch](https://github.com/yannh/kubeconform/commit/ae67bb470909d9d3af0ac704ffa140e05cbc0e50) that fixes the issue - however I could not use "CompileString" directly and had to essentially copy its implementation :sweat_smile: 

Maybe this JSONSchema library could provide a way to use these convenience functions, passing a defautl Draft version, or a custom compiler? I guess our current workaround is really not too bad though :) Thanks!!

**Comment by santhosh-tekuri** [comment]
WONT_FIX

these are convenient functions like `http.Get` and `http.Post`.

just like `http.Get` and `http.Post` does not allow to pass custom `http.Client`, the same applies here.

**Comment by yannh** [comment]
Fair enough :) Thanks!
