### ISSUE TITLE
CompileString - stat .: permission denied

### ISSUE THREAD

**Issue by iamnoah** [santhosh-tekuri/jsonschema#123]
Using `CompileString` can result in errors if run in a container environment without a readable working directory, when the URL passed is not absolute. 

I understand the reason for trying to resolve the URL, but I did not expect a panic when loading an embed schema from a string that is known to be a valid. It's an easy enough error to correct (pass an absolute URL,) but detecting it requires running the code in an esoteric environment, so it's easy to accidentally make this error and only discover it at a bad time.

**Comment by santhosh-tekuri** [comment]
EXPECTED_BAHAVIOR

this is the expected behaviour. if you pass non-absolute url to `CompileString` it converts to file based absolute path.

passing absolute url to `CompileString` should work fine without working directory set
