### ISSUE TITLE
How can I validate to Python re flavor regex?

### ISSUE THREAD

**Issue by msarauer** [santhosh-tekuri/jsonschema#124]
Is there a way to validate the regex to Python re flavor regex rather than Golang regex?

I saw these changes, but I don't understand how I would make it validate to Python. https://github.com/santhosh-tekuri/jsonschema/commit/bbc9f8974f61b76d148d1230709a653234e619bd

**Comment by msarauer** [comment]
I guess I need to do something like 
```
c.Formats["regex"] = func(
```

then provide a custom validator? How can I validate Python Regex in Go code?

**Comment by santhosh-tekuri** [comment]
You have to use some golang library which provides python flavoured regex. I am not sure of any such library.

with the commit you mentioned, such library can be used in both `c.Formats["regex"]` and `Compiler.CompileRegex`

**Comment by msarauer** [comment]
If I make a change to `c.Formats["regex"]`, I assume that I don't need to change `Compiler.CompileRegex` as well? @santhosh-tekuri

**Comment by santhosh-tekuri** [comment]
You need to add both
