### ISSUE TITLE
Error when loading valid draft7 json schema

### ISSUE THREAD

**Issue by gusfcarvalho** [santhosh-tekuri/jsonschema#129]
When trying to compile a valid draft7 json schema like this one https://github.com/usnistgov/OSCAL/releases/download/v1.1.0/oscal_catalog_schema.json the tool returns an error as it cannot reference find valid ids on the schema.

After some troubleshooting, I think this might be related to [here](https://github.com/santhosh-tekuri/jsonschema/blob/master/draft.go#L55-L58) as in these cases, the definition both have an id and a reference to a common expression.

I already confirmed that changing it to `if _, ok := m["$ref"]; ok && d.version <7 ` would work, but I'm not sure the impact this would have on this tool

**Comment by santhosh-tekuri** [comment]
EXPECTED_BEHAVIOUR

`$ref` keyword does not allow other keywords in draft7. it allows from draft 2019 onwards:
      see  https://json-schema.org/draft/2019-09/release-notes.html#core-vocabulary

there is also test for this in draft 7: [check this](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/8cdfac41e37527795879e480a483997cbd6188f3/tests/draft7/ref.json#L178-L199)

the mentioned schema is using `$id` and `$ref` as siblings in draft07, which is not allowed. in draft07, if `$ref` is present, we ignore any other sibling keywords.
