### ISSUE TITLE
Validating json with json-schema

### ISSUE THREAD

**Issue by rajsenthil** [santhosh-tekuri/jsonschema#130]
I created a sample [repo](https://github.com/rajsenthil/single-window-api-go)  to validate the [json](https://github.com/rajsenthil/single-window-api-go/blob/main/schema/product01.json) against this [schema](https://github.com/rajsenthil/single-window-api-go/blob/main/schema/product-attr-validation-schema.json) with the [simple code](https://github.com/rajsenthil/single-window-api-go/blob/main/main.go). 
I am getting the error as `invalid jsonType: *main.Product`.
Please take a look.

**Comment by rajsenthil** [comment]
appreciate your response

**Comment by santhosh-tekuri** [comment]
this is the expected behaviour;

the documentation clearly says value must be raw json value

i.e it must be string, boolean, number, map, array and composite of these.

User defined structs are not allowed in value

**Comment by santhosh-tekuri** [comment]
to be clear: you must unmarshal json into `interface{}` instead of `Product`

**Comment by rajsenthil** [comment]
Thanks for the response. It works with `interface{}`.
