### ISSUE TITLE
Support for $defs and definition keyword in Schema object.

### ISSUE THREAD

**Issue by punit-kulal** [santhosh-tekuri/jsonschema#134]
Currently the schema object does not have a property to hold schema definition(defined by `definitions` or `$defs` keyword  defined by the top level schema. Any plans to add the field to do the same. Since, if the schemas aren't referenced, they aren't available to be referenced in the top level schema.

**Comment by maribowman** [comment]
I've got the same issue. This is just a small snippet of my huge json schema with the error message below.

```json
[...]
"filter": {
                "type": "object",
                "required": [
                  "objective"
                ],
                "properties": {
                  "$ref": "#/$defs/objective"
                }
              },
[...]
```

`jsonschema file:///.../config-v2-schema.json compilation failed: '/properties/v2/properties/account/items/properties/filter/properties/$ref' does not validate with https://json-schema.org/draft/2020-12/schema#/allOf/1/$ref/properties/properties/additionalProperties/$dynamicRef/allOf/1/$ref/properties/properties/additionalProperties/$dynamicRef/allOf/1/$ref/properties/items/$dynamicRef/allOf/1/$ref/properties/properties/additionalProperties/$dynamicRef/allOf/1/$ref/properties/properties/additionalProperties/$dynamicRef/type: expected object or boolean, but got string`

**Comment by punit-kulal** [comment]
I don't think the error is related to the issue, in your case, the $defs resolution is working, it's just that your jsonschema is incompatible with draft 2020 spec.  @maribowman
