### ISSUE TITLE
Feature: Adding Context to Validate Method

### ISSUE THREAD

**Issue by voronovmaksim** [santhosh-tekuri/jsonschema#153]
I hope this message finds you well. I wanted to reach out to express my gratitude for the wonderful tool you've developed.
 
I would like to suggest adding support for `context.Context` as an input parameter to the `Validate` method:
````
func (s *Schema) ValidateCtx(ctx context.Context,v interface{}) (err error) {
	return s.validateValue(v, "")
}
````
The context would be passed to everywhere. I believe having `ctx` available in `jsonschema.ValidationContext` would be highly beneficial.

I noticed that [go-playground/validator](https://github.com/go-playground/validator/blob/a0f74b0fb2a7ae1750c0f0b0a49550d8b6e2e708/validator_instance.go#L376)  has already implemented support for context.

I can do it myself and prepare PR if you approve this feature

Thanks again for your efforts.

**Comment by voronovmaksim** [comment]
I didn't specify use case: i make call to database in `Validate`.

I've done bad WA which works only if `jsonschema.NewCompiler()` is not singelton. Maybe you tell me the better solution. I guess the compiler must be singleton in production.
 
I simply passed the ctx through my own ExtCompiler and ExtSchema, like this:"
````
ctx:= context.Context
compiler := jsonschema.NewCompiler()
compiler.RegisterExtension("mgsFormat", MgsFormatMeta, mgsFormatCompiler{Ctx})
````
`mgsFormatCompiler:`
````
type mgsFormatCompiler struct {
	ctx context.Context
}

func (compiler mgsFormatCompiler) Compile(ctx jsonschema.CompilerContext, m map[string]interface{}) (jsonschema.ExtSchema, error) {
	if mgsFormatRaw, ok := m["mgsFormat"]; ok {
		return compiledMgsFormat{compiler.ctx}, nil
	}

	return nil, nil
}
````

`compiledMgsFormat`
````
type compiledMgsFormat struct {
	ctx context.Context
}
func (f compiledMgsFormat) Validate(ctx jsonschema.ValidationContext, v interface{}) error {
  ctx := f.ctx
  //call to DB
}
````

**Comment by santhosh-tekuri** [comment]
@voronovmaksim 

ideally schema validation must be pure. I mean, if you repeatedly validate a json with schema, then it should always produce same result. if you have keyword that is making decisions based on the data from a database this will break.

ideally keywords are not supposed to do any IO during validation. So I am not keen in adding `context.Context` to `Validate` Method

but as a workaround for your use case:

you would want to pass different `context.Context` for each validation. but the code you shown above is capturing `ctx` during compilation. If you are always compiling before each validation (i.e discarding compiling schema after each validation) it might work

you can use `https://github.com/timandy/routine` to pass context. but it uses internal goroutine ID for this (which may change in future Golang versions). you can use it as follows:

```golang
import "github.com/timandy/routine"

// create global variable for holding thread local context
var threadLocal = routine.NewThreadLocal[*context.Context]()

func doSchemaValidation(ctx *context.Context, sch *Schema, instance interface{}) error {
     threadLocal.set(ctx)
}

type compiledMgsFormat struct {}
func (f compiledMgsFormat) Validate(ctx jsonschema.ValidationContext, v interface{}) error {
  ctx := threadLocal.get()
  //call to DB
}
```
