### ISSUE TITLE
Create JSONSchema from Compile()'s result

### ISSUE THREAD

**Issue by anees-a** [santhosh-tekuri/jsonschema#155]
I have a big schema that is broken down in to many files - by design - as a part of legacy code. It would make it very easy for me if there is a way to dump the Schema when created using Compile() in to a single file so that I can use that file on any online json schema validator tool for quick checks.

I am new to all this. Thus the question. Any pointers would be great.

**Comment by anees-a** [comment]
@santhosh-tekuri ^

**Comment by santhosh-tekuri** [comment]
NOT_PLANNED

Merging multiple schema documents into single schema is called `bundling`.

Bundling is not in the scope of this project. But you can try https://github.com/APIDevTools/json-schema-ref-parser which supports bundling feature.
