### ISSUE TITLE
Wrong unevaluatedProperties validation errors

### ISSUE THREAD

**Issue by vassilvk** [santhosh-tekuri/jsonschema#156]
Consider the following schema which uses `unevaluatedProperties` in order to extend a closed schema following [the official JSON schema documentation](https://json-schema.org/understanding-json-schema/reference/object#unevaluatedproperties):

**schema.json**
```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  ],
  "properties": {
    "type": { "enum": ["residential", "business"] }
  },
  "required": ["type"],
  "unevaluatedProperties": false
}
```

When running `jv` against the following *valid* document:

**doc.json**

```json
{
  "street_address": "123 Willow Road",
  "city": "Middletown",
  "state": "KY",
  "type": "residential"
}
```

... `jv` validates the document as expected:

```bash
$ jv schema.json doc.json
$
```

Now, if we make the document invalid by modifying one of the subschema properties - for example, by setting the `street_address` to a number:

```json
{
  "street_address": 12,
  "city": "Middletown",
  "state": "KY",
  "type": "whatever"
}
```

... `jv` correctly detects the `street_address` type mismatch, however it also yields an `unevaluatedProperties not allowed` error for every property that's declared by the subschema, although these properties are correct according to the schema:

```bash
$ jv schema.json doc.json
[I#] [S#] doesn't validate with file:///Users/vassilk/projects/test/json/schema.json#
  [I#] [S#/allOf/0] allOf failed
    [I#/street_address] [S#/allOf/0/properties/street_address/type] expected string, but got number
  [I#/state] [S#/unevaluatedProperties] not allowed
  [I#/street_address] [S#/unevaluatedProperties] not allowed
  [I#/city] [S#/unevaluatedProperties] not allowed
```

**Comment by santhosh-tekuri** [comment]
@vassilvk 

I am unable to reproduce this issue; for me it says the `doc.json` is valid against `schema.json`

 please make sure you have latest `jv@v0.6.0` installed as shown below:

```
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
go: downloading github.com/santhosh-tekuri/jsonschema/cmd/jv v0.6.0
$ go version -m `which jv`
/Users/santhosh/go/bin/jv: go1.21.1
        path    github.com/santhosh-tekuri/jsonschema/cmd/jv
        mod     github.com/santhosh-tekuri/jsonschema/cmd/jv    v0.6.0  h1:cZwlzkrhvGz6S77UVwfhoDMjzOznZX/hNtbNfaWMZg8=
        dep     github.com/santhosh-tekuri/jsonschema/v5        v5.3.1  h1:lZUw3E0/J3roVtGQ+SCrUrg3ON6NgVqpn3+iol9aGu4=
        dep     gopkg.in/yaml.v3        v3.0.1  h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
        build   -buildmode=exe
        build   -compiler=gc
        build   DefaultGODEBUG=panicnil=1
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=arm64
        build   GOOS=darwin
```

**Comment by santhosh-tekuri** [comment]
from the error message you have, I see:

```
[I#/street_address] [S#/allOf/0/properties/street_address/type] expected string, but got number
```

which clearly says that `street_address` in your document is number, not string

I guess, you are validating with wrong `doc.json`. please recheck

**Comment by santhosh-tekuri** [comment]
from spec:

https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#name-unevaluatedproperties
```
The behavior of this keyword depends on the annotation results of adjacent keywords that apply to the instance location being validated.
```

but `annotation results` are generated only when an instance is valid against schema. see https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#name-annotations

```
JSON Schema can annotate an instance with information, whenever the instance validates against the schema object containing the annotation, and all of its parent schema objects.
```

**Comment by santhosh-tekuri** [comment]
to better understand consider following example:

consider following files:

schema.json: ( `allOf` is wrapped in `not` )
```json
{
  "allOf": [ { "not":
    {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  }],
  "properties": {
    "type": { "enum": ["residential", "business"] }
  },
  "required": ["type"],
  "unevaluatedProperties": false
}
```

```doc.json
{
  "street_address": 123,
  "city": "Middletown",
  "state": "KY",
  "type": "residential"
}
```

here `street_address` is number so `allOf` fails which implies `not` succeeds. still validator considers that none of the properties are evaluated

see `jv` output below:
```
jv schema.json doc.json
[I#] [S#] doesn't validate with file:///Users/santhosh/gh/santhosh-tekuri/jsonschema/cmd/jv/schema.json#
  [I#/street_address] [S#/unevaluatedProperties] not allowed
  [I#/city] [S#/unevaluatedProperties] not allowed
  [I#/state] [S#/unevaluatedProperties] not allowed
```

if you want you can also check results at https://www.jsonschemavalidator.net

**Comment by vassilvk** [comment]
> @vassilvk
> the second document you have specified is invalid;

Yes, this was the main point.
The second document has one issue, and I expect to see one validation error.
Seeing validation errors for all the other properties (which are in fact valid) makes no sense and is potentially confusing.

**Comment by santhosh-tekuri** [comment]
in the beginning, this library used to show only single error and stop validation on first error.

later ability to show multiple errors is added.

It is always not trivial to show errors from customer's perspective.

for example when missing a semicolon in a program, compiler shows tons of errors. it is similar situation here.

we can do stop validating keywords that have dependent on other keywords. but it is little complicated to implement and maintain.

**Comment by vassilvk** [comment]
I understand. Thank you for the quick response and thank you for a great library!

**Comment by reitzig** [comment]
FWIW, I was confused by this as well and landed here.

Sketching:

```json
{
  "$schema" :               "https://json-schema.org/draft/2020-12/schema",
  "$ref" : "request-common.schema.json#/$defs/base",
  "unevaluatedProperties" : false
}
```

Say all but one property defined in `base` are valid. I get:

```
jsonschema validation failed with 'my-mock.schema.json#'
- at '/propA': validation failed
  - at '/propA/0': got string, want number
- at '/propB': false schema
- at '/propC': false schema
- at '/propD': false schema
```

I understand that it's hard to pick out the "right" errors. However, _because_ `jv` usually evaluates all properties and reports all errors, this behaviour actively misled me. `propB` et al _have_ been succesfully validated (or so I assume), so I thought I'd misunderstood how `unevaluatedProperties` works.

> JSON Schema can annotate an instance with information, whenever the instance validates against the schema object containing the annotation, and all of its parent schema objects.

Not sure if this should be taken literally in this case, btw. Apparently, validators can opt out of annotations entirely (ref: [json-schema-org#236.3713637](https://github.com/orgs/json-schema-org/discussions/236#discussioncomment-3713637)), which would render `unevaluatedProperties` completely inert, or rather breaking. Just a thought, not trying to convince you. If it's just an inconvenient gap in the current draft, we'll have to live with it.

I'll have to consider how to teach my users to ignore those false errors, and future me as well. 🤔

**Comment by santhosh-tekuri** [comment]
@reitzig 

assuming `base` has validation for `propA`. then in main schema `unevaluatedProperties` is applied all the other properties other than `propA` irrespective of whether `propA` is valid/invalid as per `base`

in simple terms, `unevaluatedProperties` says, if a property is not validated by any other keyword, then only I will validate that property

**Comment by reitzig** [comment]
Ah, I should have been clearer. `prop[ABCD]` _all_ have validators in `base`. As soon as I fix the error in `propA`, the other three error messages go away. Therefore, I consider them false errors.

**Comment by vassilvk** [comment]
For what it's worth, we solved the problem by implementing our own extension keyword that implemented the semantics of `unevaluatedProperties`, and we ditched `unevaluatedProperties` from our schemas altogether.
