### ISSUE TITLE
Missing document file path in validation output when validating multiple documents

### ISSUE THREAD

**Issue by ahochsteger** [santhosh-tekuri/jsonschema#163]
Currently the `jv` cli only outputs the validation results but omits the information about the corresponding document the validation results belong to.
This is especially problematic when validating multiple documents at once.
Even with detailed output I just get this:
```
jv -output detailed path-to/myschema.json *.json
{
  "valid": true
}
{
  "valid": true
}
```
Or is there a way to enable this information?

**Comment by santhosh-tekuri** [comment]
@ahochsteger there is no flag available for this.
I just added this information with d3bf053

**Comment by ahochsteger** [comment]
@santhosh-tekuri wow, that was quick - thanks a lot! :smiley: 
Since I use it as part of an build pipeline with automated reporting it would be great to have the instance as part of the JSON output. Currently it breaks the processing, since the output is now mixed plain text and JSON.

It also seems, that currently the output JSON switches from stdout to stderr if validation errors are found, which makes post-processing a pain, since I have to redirect stderr to stdout (2>&1) which may still break if there are any non-JSON error messages which should stay at stderr. Best would be if JSON would always be in stderr and additional (text) messages always to stderr.

Let me know, if you think I should open a separate issue for that.

**Comment by santhosh-tekuri** [comment]
@ahochsteger 
I am rewriting this package. You can find the latest one at: 
    https://github.com/santhosh-tekuri/jsonschema/blob/boon/cmd/jv/main.go

it has more consistent output and also has `-q` quite mode

it has better output for parsing.

You can try the latest one if possible. otherwise let me know if adding `-q` quite flag solves your trouble

**Comment by ahochsteger** [comment]
@santhosh-tekuri I just tried the `boon` branch, but it gives me this error:
```
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@boon
go: downloading github.com/santhosh-tekuri/jsonschema/v6 v6.0.0
../../../../go/pkg/mod/github.com/santhosh-tekuri/jsonschema/cmd/jv@v0.0.0-20240502123112-148d5f7e16ea/loader.go:13:2: reading github.com/santhosh-tekuri/jsonschema/go.mod at revision v6.0.0: unknown revision v6.0.0
```

**Comment by santhosh-tekuri** [comment]
the branch `boon` is not published yet. so `go install` will not work.

you have to clone the repo and build it from sources as shown below:

```
$ git clone https://github.com/santhosh-tekuri/jsonschema.git
Cloning into 'jsonschema'...
remote: Enumerating objects: 3960, done.
remote: Counting objects: 100% (1737/1737), done.
remote: Compressing objects: 100% (589/589), done.
remote: Total 3960 (delta 1178), reused 1285 (delta 1113), pack-reused 2223
Receiving objects: 100% (3960/3960), 872.06 KiB | 1.19 MiB/s, done.
Resolving deltas: 100% (2821/2821), done.

$ cd jsonschema
$ git checkout boon
branch 'boon' set up to track 'origin/boon'.
Switched to a new branch 'boon'
$ go build ./cmd/jv
$ ./jv -h
Usage: jv [OPTIONS] SCHEMA [INSTANCE...]

Options:
  -c    Enable content assertions with draft >= 7
  -cacert PEM-certificate-file
        Use the specified PEM-certificate-file to verify the peer. The file may contain multiple CA certificates
  -d version
        Draft version used when '$schema' is missing. Valid values 4, 6, 7, 2019, 2020 (default 2020)
  -f    Enable format assertions with draft >= 2019
  -h    Print help information
  -k    Use insecure TLS connection
  -o format
        Output format. Valid values simple, alt, flag, basic, detailed (default "simple")
  -q    Do not print errors
```

NOTE: the command line flags are bit different compared to original
