### ISSUE TITLE
ECMA-262 as the default regex in this library?

### ISSUE THREAD

**Issue by crowdwave** [santhosh-tekuri/jsonschema#167]
Given that the standard says it should be ECMA-262 shouldn't that be what this lib does by default?

**Comment by santhosh-tekuri** [comment]
[WONT_FIX]

in RFC `Should be` means recommended(not mandatory). `Must be` means mandatory

https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-regular-expressions

the above section explains what are the requirements of regular expression support

Further I don't want to third party dependency by default. For most schema regexp from std is sufficient.
For speicial situations, they can plugin custom regexp engine.
