### ISSUE TITLE
Cannot install older version than `@latest`

### ISSUE THREAD

**Issue by frostmar** [santhosh-tekuri/jsonschema#175]
The readme gives this install command, for the latest version:
`go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest`

The recent v6 release requires a higher golang version, so I wanted to install the last v5 release. 
However I think it's not possible, due to the submodule in package cmd/jv ?

This happens:
```
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v5.3.1

go: github.com/santhosh-tekuri/jsonschema/cmd/jv@v5.3.1: github.com/santhosh-tekuri/jsonschema/cmd/jv@v5.3.1: invalid version: unknown revision cmd/jv/v5.3.1
```

```
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v5

go: github.com/santhosh-tekuri/jsonschema/cmd/jv@v5: no matching versions for query "v5"
```

**Comment by santhosh-tekuri** [comment]
the library and cli are versioned independently

latest version of cli is `v0.7.0`. You can check it in tags, you will find `cmd/jv/v0.7.0`

to install previous version try following:

```
go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v0.6.0
```

**Comment by frostmar** [comment]
thanks, it would be helpful to explain that in the readme, with some way to find which versions of the CLI exist

**Comment by santhosh-tekuri** [comment]
done 89d3b9e
