### ISSUE TITLE
Support for extensions.

### ISSUE THREAD

**Issue by matthewpeterkort** [santhosh-tekuri/jsonschema#197]
Hi. Are Extensions still supported in the current jsonschema boon branch? I am trying to migrate to the newest version and noticed that functions like ```func (c *Compiler) RegisterExtension(name string, meta *Schema, ext ExtCompiler) {``` no longer exist.

**Comment by santhosh-tekuri** [comment]
See examples.
example_vocab_discriminator_test.go

example_vocab_uniquekeys_test.go

Extensions are renamed to vocabularies

**Comment by matthewpeterkort** [comment]
Thank you. What is the equivalent function for  `func (ctx CompilerContext) CompileRef(ref string, refPath string, applicableOnSameInstance bool) (*Schema, error) {` In the newest version?

**Comment by santhosh-tekuri** [comment]
it is `Vocabulary.Compile`
