### ISSUE TITLE
Differentiate between array elements and keys for InstanceLocation

### ISSUE THREAD

**Issue by titus-ong** [santhosh-tekuri/jsonschema#198]
Currently, the `InstanceLocation` for some element of an array and a key of an object that is that element's index look extremely similar.

Schema:
```
{
  "$id": "schema.json",
  "title": "Example",
  "type": "object",
  "properties": {
    "address": {
      "type": "object",
      "properties": {
		"streets": {
		  "type": "array",
		  "items": {
			"type": "string",
			"minLength": 1
		  }
		},
		"alleys": {
		  "type": "object",
		  "properties": {
			"1": {
			  "type": "string",
			  "minLength": 1
			}
		  }
		}
      },
      "required": ["streets", "alleys"]
    }
  },
  "required": ["address"]
}
```

Instance:
```
{
  "address": {
	"streets": ["Palace Road", ""],
	"alleys": {"1": ""}
  }
}
```

The validation error from this instance will result in two errors, one at `/address/streets/1` and `/address/alleys/1`. As a result, it's quite difficult to navigate to the correct item/key in golang since we have to differentiate unmarshalling `streets` and `alleys` into `[]string` and `map[string]any` respectively. 

I suggest using the standard `[]` notation for array elements, e.g. in this case, the two errors will have instance locations of `/address/streets[1]` and `/address/alleys/1`.

Side note: is there any documentation on error handling? The examples given in godoc do not handle any of the validation errors. For instance, I'm trying to figure out why ErrorKind.KeywordPath() returns a string slice, in my testing so far I have only encountered 1 item in the slice e.g. "minLength" even if the validation error is nested.

**Comment by santhosh-tekuri** [comment]
it is defined as such in [JSONPointer Specification](https://datatracker.ietf.org/doc/html/rfc6901)

even adding `[]` does not solve issue. json could have a property named `[1]`

the solution is: check the json object type. if it is of type `map` then it is property name, else if it is array it is index, otherwise it is an error
