### ISSUE TITLE
Override LoadURL at Compiler

### ISSUE THREAD

**Issue by jfancher** [santhosh-tekuri/jsonschema#26]
I'm implementing a feature that will allow schemas to be stored and updated; the details aren't very relevant, but the key point is that a schema URL may not have a globally-consistent referent (for instance, the current value vs one being updated). Thus, I'm finding the global `LoadURL` function to be limiting as a resolution strategy.

It seems like a simple solution would be to make the loader function local to the `Compiler` object (and initialized to the global). Does this change make sense? If so, I would be happy to send a PR.

**Comment by santhosh-tekuri** [comment]
makes sense. you can send PR.
