### ISSUE TITLE
Add resource source map to `Schema` to support custom keywords

### ISSUE THREAD

**Issue by aeneasr** [santhosh-tekuri/jsonschema#32]
First of all, this library is amazing because it allows one to actually traverse a JSON Schema outside of the library (and nice solve with recursion through pointers). I wish I had found it 3 months ago!

I would like to expose the "raw" data for each schema to the outside. It would be fairly simple by basically adding a new field `Raw map[string]interface{}` (or alternatively a function that exposes the internal `raw` as to avoid potential future BC breaks in case where "raw" would be added to the schema). The field would be populated in `compileMap`.

Custom keywords are supported, for example, in ajv: https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md

I also believe that I've read somewhere that Draft8 will have room for custom keywords (not 100% sure)?

While this approach is well short of actually "embedding" the custom keyword in this library, it would at least allow the consumer of that library to have access to that data.

**Comment by aeneasr** [comment]
Actually, as I'm thinking about this - while the raw data is interesting, it actually needs context of the data structure we're validating. 

ajv supports this by defining callbacks: 

```
ajv.addKeyword('constant', {
  validate: function (schema, data) {
    return typeof schema == 'object' && schema !== null
            ? deepEqual(schema, data)
            : schema === data;
  },
  errors: false
});
```

What's pretty cool is that they support custom compilation too:

```
ajv.addKeyword('range', {
  type: 'number',
  compile: function (sch, parentSchema) {
    var min = sch[0];
    var max = sch[1];

    return parentSchema.exclusiveRange === true
            ? function (data) { return data > min && data < max; }
            : function (data) { return data >= min && data <= max; }
  },
  errors: false,
  metaSchema: {
    type: 'array',
    items: [
      { type: 'number' },
      { type: 'number' }
    ],
    additionalItems: false
  }
});
````

but while that's awesome it might be a bit much for now (though definitely possible).

How about adding a new method such as `AddKeyword(keyword string, KeywordOptions{})` with e.g. `Validate func(keyword interface{}, data interface{}) error` as a starter?

**Comment by santhosh-tekuri** [comment]
actually first cut implementation actually stores only map[string]interface{} and validators are pluggable. later i added compilation to library for performance reasons.

I think adding custom compilation with validation is better approach without storing raw schema content. will brainstorm on this.

**Comment by aeneasr** [comment]
> actually first cut implementation actually stores only map[string]interface{} and validators are pluggable. later i added compilation to library for performance reasons.

I think this is still legitimate and it works very nicely with the pointer recursion. As far as I can tell, the current layout is truly superb. I wouldn't walk back on that, maybe just adding a simple extension field to enable this particular use case is enough.

**Comment by handrews** [comment]
@santhosh-tekuri @aeneasr Draft `2019-09` (formerly known as `draft-08`) [has been published](http://json-schema.org/specification.html) and does indeed provide formal support for extension vocabularies.

We're still working on detailed guidance fo this, but here's a quick summary:

* Meta-schemas still describe/validate schemas
* An optional part of describing a schema with a meta-schema is to use the `$vocabulary` keyword to declare what sets of keywords are used and with what semantics, and whether they are required to successfully process the schema or not
* `$vocabulary` has to be declared in the root schema object of the meta-schema.  You can't `allOf`/`anyOf`/etc. it (at least not with this draft- it got too complicated so we kept it simple and will see what feedback we get)
* There are other features (`$recursiveRef` and `$recursiveAnchor`) that make it _much_ easier to extend the standard meta-schemas.  It is no longer necessary to repeat the definitions of keywords that take subschemas as values.
* `$vocabulary` values include a URI which a generic implementation can use to identify some sort of plug-in to load to handle the keywords (we've left this a little vague so as not to overly constrain implementations- if some good practices emerge we may add them in the next draft)
* The draft also includes more general guidance on what kinds of things keywords are able to do, and how those things work

We're going to be really pushing `2019-09` as the new baseline, and _hopefully_ the last really major update before proper standardization.  There are some things that are still under-specified with vocabularies (for example, there's no machine-readable vocabulary description- we need feedback on what it should contain).

Note that OpenAPI 3.1 will have full compatibility with JSON Schema draft `2019-09`, which heals the biggest rift in the JSON Schema user community.

**Comment by handrews** [comment]
Please drop in on the [JSON Schema slack](https://join.slack.com/t/json-schema/shared_invite/enQtNjc5NTk0MzkzODg5LTVlZGIxNmVhMGY2MWFlYTdiNDQ5NWFiZGUwOThhNmYxZDE0YzA5YjRiOTA5MGY4ZTZlZGZhZDFmYTY4NWM2N2Y) with any questions on how to implement or use these features!

**Comment by santhosh-tekuri** [comment]
@aeneasr extensions are implemented in 6f0123312bb8a97a3aaa925d9ee5df6b4203049f

examples, docs and tests are still pending

**Comment by aeneasr** [comment]
Wow that was quick - thank you!

**Comment by aeneasr** [comment]
@handrews wow great to see the new draft is released!

**Comment by santhosh-tekuri** [comment]
sample `powerOf` extension included in tests. see https://github.com/santhosh-tekuri/jsonschema/blob/extensions/extension_test.go

**Comment by santhosh-tekuri** [comment]
documentation is added

**Comment by aeneasr** [comment]
I was finally able to get back to this and am really happy with the way you solved the extensions. I've written a small fix for the tests. In my opinion, this is good to merge!

**Comment by santhosh-tekuri** [comment]
custom extensions is released in v2.2.0

**Comment by joeriddles** [comment]
@santhosh-tekuri were extensions removed in v6? I no longer see them.

**Comment by santhosh-tekuri** [comment]
They are renamed to vocabulary. See example_vocab_*.go files
