### ISSUE TITLE
Regression in "validation passed" output message

### ISSUE THREAD

**Issue by narutoshocker** [santhosh-tekuri/jsonschema#34]
Previous versions of the jsonschema would validate a json file, and if there were no errors, would print out a timestamp and the message "Passed validation".

However, the current system no longer prints a message when validation is passed. It would be nice to obtain some form of notification that the schema was validated and actually passed, versus assuming that no output is a good thing.

Current behavior when validation passed:

Previous behavior when validation passed:
"HMIschemavalidator 2019/11/27 13:57:22 Passed validation"

**Comment by santhosh-tekuri** [comment]
this is a library. and does not print any thing to console even in previous versions.
if you are sure that is the case, provide details of version and sample code to reproduce the issue

**Comment by narutoshocker** [comment]
I honestly have no idea what version it was nor how to obtain it. But I do
have snippets of the output where this string is seen.

**Comment by santhosh-tekuri** [comment]
"Passed validation" such string is never used in this library. it must be getting printed from your library.
