### ISSUE TITLE
No support for optional output of errors into a file (more improvement than a bug)

### ISSUE THREAD

**Issue by narutoshocker** [santhosh-tekuri/jsonschema#35]
I've noticed that the range of errors can sometimes extend past the window/line size of different cmd windows.

It would be great if the errors would spit into a file so that users can see all issues cleanly.

**Comment by santhosh-tekuri** [comment]
the library never prints validations errors to console.

**Comment by santhosh-tekuri** [comment]
the api returns error. it does not write errors to file

**Comment by narutoshocker** [comment]
You are correct. I reviewed the external script to see where the outputs are. Apologies.
