### ISSUE TITLE
Meta-schema URIs should support https and optional trailing hash

### ISSUE THREAD

**Issue by smoya** [santhosh-tekuri/jsonschema#40]
From Draft 2019-09, all meta-schema URIs use `https`. 
Even though this library only supports Draft-07 or lower, still needs to support meta-schema URIs with `https`.
Also, the trailing `#` is completely optional.

For example: https://json-schema.org/draft-07/schema

**Comment by santhosh-tekuri** [comment]
bumped from `v3.0.1` to `v3.0.2`

**Comment by smoya** [comment]
Wow, that was so fast @santhosh-tekuri 👏  Thanks
