### ISSUE TITLE
go install installs old version

### ISSUE THREAD

**Issue by theory** [santhosh-tekuri/jsonschema#42]
Wanted to install `jv` 5.0, but `go install` couldn't figure it out:

```
$ go version
go version go1.17.1 darwin/amd64
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v5 
go install: github.com/santhosh-tekuri/jsonschema/cmd/jv@v5: no matching versions for query "v5"
```

Using `@latest` works, but installs v1:

```
$ go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
go: downloading github.com/santhosh-tekuri/jsonschema v1.2.4
```

Not sure if this is a go issue or if the repo needs a `cmd/jv/go.mod` file to fix it.

**Comment by theory** [comment]
I guess it's because `cmd/jv` isn't versioned like the library is.

**Comment by santhosh-tekuri** [comment]
i am not sure whether `go.mod` should be added in `cmd/jv`

but noticed that following command works:

```
go install github.com/santhosh-tekuri/jsonschema/v5/cmd/jv@latest
```

**Comment by theory** [comment]
Oh! Just need to put the v5 in the right place I guess. This stuff is so opaque.

**Comment by decentralgabe** [comment]
ran into this as well, would be good to add to the README

**Comment by santhosh-tekuri** [comment]
@decentralgabe this is already added into GitHub README in 6fcf576
