### ISSUE TITLE
Adding json tags to Schema type

### ISSUE THREAD

**Issue by hbagdi** [santhosh-tekuri/jsonschema#45]
I would like to use the [Schema](https://github.com/santhosh-tekuri/jsonschema/blob/b963b098e9f92f8eac8f3d310551fdf76388d378/schema.go#L15) type to programmatically generate the JSON schema itself.

Would you be open to accepting such an addition to the code?

Example:
```go
type Schema struct {
	Location string `json:"location,omitempty"` // absolute location
.
.
.

```

**Comment by santhosh-tekuri** [comment]
Schema is never intended to regenerate json schema back. it is compiled representation that is suitable for validation purposes.

even if you add json tags, it will not work, you can not construct schema references and there are chances of running into infinite recursion during json marshal
