### ISSUE TITLE
`"items"` can be a `bool` in 2020

### ISSUE THREAD

**Issue by chanced** [santhosh-tekuri/jsonschema#49]
see the **Closed tuple** example in the 2020 release notes https://json-schema.org/draft/2020-12/release-notes.html

```json
{
  "prefixItems": [
    { "$ref": "#/$defs/foo" },
    { "$ref": "#/$defs/bar" }
  ],
  "items": false
}
```

**Comment by chanced** [comment]
Also, thanks for the awesome package. 

In addition to the functionality your package provides, I need to be able to simply marshal/unmarshal into json/yaml. That alone has been a nontrivial lift. My point is, much respect for getting compilation/validation working!

**Comment by santhosh-tekuri** [comment]
yes. in 2020 release, `items` can take boolean value.
but in 2020 release, boolean value is a valid schema.

so in 2020 release, `items` is compiled into boolean schema if it is boolean.

to be precise:

```json
{ "items": false }
```

compiles into:
```go
&Schema{
    Items2020: &Schema{ Always: &false },
}
```

similarly:

```json
{ "items": true }
```

compiles into:
```go
&Schema{
    Items2020: &Schema{ Always: &true },
}
```

**Comment by chanced** [comment]
Aaaahh, thank you! Sorry for the erroneous ticket!

**Comment by santhosh-tekuri** [comment]
It's fine. Not an issue
