### ISSUE TITLE
Feature: support for meta-schemas

### ISSUE THREAD

**Issue by 0fefe** [santhosh-tekuri/jsonschema#62]
I'm trying to create a meta-schema and later on validate the schema with that meta-schema. However, when :

```
"$schema": "some_non_draft_ url"
```
It breaks. I checked that the URL only must match with a draft URL. If so, how do I implement a meta-schema?

**Comment by santhosh-tekuri** [comment]
This is not yet implemented.

**Comment by handrews** [comment]
Depending on your workflow, if you don't need the custom meta-schema at runtime, as a workaround you can validate pre-existing schemas against a custom meta-schema by just treating then as a normal instance and schema.

**Comment by santhosh-tekuri** [comment]
This is fixed in v5.1.0
