### ISSUE TITLE
Forcing a schema version

### ISSUE THREAD

**Issue by royhadad** [santhosh-tekuri/jsonschema#63]
The Readme.md states that ["You can force to use specific version, when $schema is missing, as follows"](https://github.com/santhosh-tekuri/jsonschema#:~:text=You%20can%20force%20to%20use%20specific%20version%2C%20when%20%24schema%20is%20missing%2C%20as%20follows%3A).

What if I want to ignore the `$schema` key completely and always compile against a specific version?

**Comment by santhosh-tekuri** [comment]
The library has no option to achieve this.

You can remove  '$schema' attribute before feeding to the library, to achieve the behavior you described
