### ISSUE TITLE
Feature: Output compiled schema as JSON – "Schema.Marshal()"

### ISSUE THREAD

**Issue by jazzu** [santhosh-tekuri/jsonschema#82]
# The Problem

In my current project we manage many schemas, subschemas, and schemas for schemas, etc. and put them together as needed with `AddResource()`/`Compile()`. When creating new schemas, I find that finding possible mistakes is that much harder without seeing the compilation result. Hunting down possible mistakes with JSON shards is painful, with the feedback loop being too long for efficient development.

# The Solution

Schema struct could have a method `Marshal()` which is essentially the same as, for example, stdlib function `json.Marshal()`. The resulting byte slice could then be easily inspected for errors in the compiled schema.

A bonus would be `MarshalIndent()` to pretty-print the schema JSON.

**Comment by santhosh-tekuri** [comment]
i guess, if there is an error in another schema which is ref-ed from original schema, currently the error returned does not say which schema file has error. it always says the error is in main schema file.

if it is so, let me know. that is a bug and needs to be fixed.

**Comment by jazzu** [comment]
The trouble has been mostly about understanding how the refs end up pointing, but the more I work on the tougher issues, the more I grok JSON Schema. If I run into such nested-errors-reported-at-top-level issues, I will open another issue here.

Closing this, thanks for listening :-)
