### ISSUE TITLE
panic "compilation failed: no Loader found for urn:"

### ISSUE THREAD

**Issue by danielb42** [santhosh-tekuri/jsonschema#83]
Hi there,

I'm trying to validate some json against [this](https://github.com/F5Networks/f5-appsvcs-extension/blob/master/schema/latest/as3-schema.json) schema. The first line (`"$id": "urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d",`) causes a panic however (see title). Once I remove that line, validation works fine.

Can someone take a look so that I don't have to tweak the schema before validating against it?

Thanks!

**Comment by santhosh-tekuri** [comment]
this is recently fixed after v5 in e82f010

URN support is added in this commit.

**Comment by danielb42** [comment]
Great! Thanks for the hint, works perfectly.

**Comment by santhosh-tekuri** [comment]
i just tagged v5.0.1 which includes this fix

**Comment by danielb42** [comment]
Even better :) Thank you!

**Comment by danielb42** [comment]
Hey @santhosh-tekuri, I think there's an additional dot slipped into the tag name. Go doesn't recognize it as latest..

**Comment by santhosh-tekuri** [comment]
thanks for pointing. I used git release ui to create tag, which seems messed with the name.
corrected now.
