### ISSUE TITLE
Compiler ignores extensions if there is $ref and draft<2019

### ISSUE THREAD

**Issue by bserdar** [santhosh-tekuri/jsonschema#84]
If there is $ref, everything is ignored if draft<2019 during compilation, but should the extensions be ignored as well? They are extensions by definition, and it makes sense to compile them even if there is $ref.

**Comment by bserdar** [comment]
Properties of a $ref should be ignored during validation but during compilation? The spec doesn't talk about compilation at all.

There are many schemas out there that have "description" fields for $ref. We are losing those. We also have metadata extensions associated with $ref. They do not affect validation, but I was hoping to get those via compilation.

**Comment by santhosh-tekuri** [comment]
Compilation is an implementation detail and specification will not talk about that. It is possible to implement jsonSchema without compilation phase. this library choses to have compilation to avoid ref resolution, recursion tracking etc for each validation.

it may be possible to capture annotations during compilation for $ref, as they are not used in validation. but compiling extensions is not possible. there is no way to find whether extension is just using metadata and does not affect validation.

i would suggest you to open a community discussion at https://github.com/json-schema-org/community/discussions, for further clarification. that would help us to find out what should be the correct behaviour.

**Comment by bserdar** [comment]
As you said, compilation is an implementation detail. The $ref check should be done in validation, not compilation. I don't think a community discussion would go anywhere about an implementation detail. The behavior specification is about validation, not compilation.

Compilation simply gives a parsed and linked schema. By ignoring elements of $ref, compilation is doing an incomplete parse. This is an actual case that exists in the field, and it is not limited to "description" elements in a $ref object. The referenced object and the referencing object have two different identities, the referenced one is a structure definition, and the referencing one is an instance using that structure. If you want to annotate a schema using extensions, annotations for the referenced object annotate all instances, whereas annotating the referencing object annotates that particular instance. So there is a valid use case for allowing extensions for $ref while still keeping the validation compliant to spec.

**Comment by santhosh-tekuri** [comment]
this is the expected behaviour
