### ISSUE TITLE
jsonschema:invalid jsonType: uint 

### ISSUE THREAD

**Issue by 23233** [santhosh-tekuri/jsonschema#85]
Hi~ 

Why  `jsonType` Funciton not support uint and more golang number type? 
```
	case json.Number, float64, int, int32, int64:
		return "number"
```

If want use `uin8` or `float32` , Have some suggestion?

Thanks~

**Comment by santhosh-tekuri** [comment]
`json.Unmarshal` uses only `float64` or `json.Number` for numbers.

rest of them were added for convenience.

BTW, are you getting those types from `yaml.Unmarshal` ?

**Comment by santhosh-tekuri** [comment]
fixed by cf86572

**Comment by santhosh-tekuri** [comment]
created v5.0.2

**Comment by yoanm** [comment]
Perfect, thank you 👌
