### ISSUE TITLE
format not validated

### ISSUE THREAD

**Issue by naivary** [santhosh-tekuri/jsonschema#94]
Hi. I just tested multiple default formats which are implemented by the package but the validation is not forced. It gets always ignored. Can you verify that?

**Comment by naivary** [comment]
PS: Solved the problem. `Compiler.AssertFormat` is per definition of the Jsonschema Draf-07 false by default. Create a new Compiler and set AssertFormat to true.

**Comment by santhosh-tekuri** [comment]
for draft4,6,7 formats are always validated. 
for draft 2019, 2020 there are validated if `Compiler.AssertFormat` is `true`

**Comment by santhosh-tekuri** [comment]
it must be always validated in draft7. seems recent cleanup introduced the bug
fixed in b4ca7e3
